services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
    ports:
      - 8080:8080
    
