services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magicmirror.entrypoints=http"
      - "traefik.http.routers.magicmirror.rule=Host(`magicmirror.cassar.online`)"
      - "traefik.http.middlewares.magicmirror-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.magicmirror.middlewares=magicmirror-https-redirect"
      - "traefik.http.routers.magicmirror-secure.entrypoints=https"
      - "traefik.http.routers.magicmirror-secure.rule=Host(`magicmirror.cassar.online`)"
      - "traefik.http.routers.magicmirror-secure.tls=true"
      - "traefik.http.routers.magicmirror-secure.service=magicmirror"
      - "traefik.http.services.magicmirror.loadbalancer.server.port=7575"
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
    ports:
      - 8080:8080
