---
- hosts: all
  become: yes
  roles:
    - ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 192.168.5.11
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5
