---
- hosts: all
  become: true
  roles:
    - wazuh-ansible/roles/wazuh/ansible-wazuh-agent
  vars:
    - wazuh_manager_ip: "{{ WAZUH_MANAGER }}"
    - wazuh_registration_password: "{{ WAZUH_REGISTRATION_PASSWORD }}"
    - wazuh_autoupdate: true
    - wazuh_agent_name: "{{ ansible_hostname }}"

#  tasks:
#    - name: Register Wazuh Agent
#      command: /var/ossec/bin/agent-auth -m {{ WAZUH_MANAGER }} -A {{ ansible_hostname }} -P {{ WAZUH_REGISTRATION_PASSWORD }}
#      register: result

      
