---
- hosts: all
  become: true
  roles:
    - wazuh-ansible/roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "{{ WAZUH_MANAGER }}"
        authd_pass: "{{ WAZUH_REGISTRATION_PASSWORD }}"
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5
    wazuh_agent_authd:
      registration_address: "{{ WAZUH_MANAGER }}"
      enable: true
      port: 1515
      agent_name: "{{ ansible_hostname }}"


#  tasks:
#    - name: Register Wazuh Agent
#      command: /var/ossec/bin/agent-auth -m {{ WAZUH_MANAGER }} -A {{ ansible_hostname }} -P {{ WAZUH_REGISTRATION_PASSWORD }}
#      register: result

      
