---
  - hosts: all
    roles:
#      - role: zabbix.zabbix.agent
      - role: /root/.ansible/collections/ansible_collections/zabbix/zabbix/roles/agent
        agent_variant: 2
        agent_major_version: 6.4
        agent_param_hostname: "{{ ansible_hostname }}"
        agent_param_server: 192.168.5.13        # address of Zabbix server to accept connections from;
        agent_param_serveractive: 192.168.5.13   # address of Zabbix server to connect using active checks;
